name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with: submodules: 'recursive'
     - uses: actions/setup-python@v4
       with: python-version: '3.10'
     - run: pip install -r src/requirements.txt || echo "no requirements"
     - run: flake8 src/ || echo "no flake8 config"
     - run: pytest tests/ || echo "no tests"
