name: Create Release
on:
  push:
    tags:
      - 'v*'
permissions: contents: write
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag"             --title "$tag"             --generate-notes
